@startuml
class MqttReceiverService {
    + MqttReceiverService(loggerFactory:ILoggerFactory, config:IConfigurationRoot, dbContextFactory:IDbContextFactory<ApplicationDbContext>)
    + <<async>> Disconnect() : Task
    + <<async>> Start(ct:CancellationToken) : Task
}
MqttReceiverService --> "Options" MqttClientOptions
@enduml
