@startuml
class ModuleModel {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Description : string? <<get>> <<set>>
    + MqttTopic : string <<get>> <<set>>
}
class "ICollection`1"<T> {
}
ModuleModel --> "CreatedAt" DateTime
ModuleModel o-> "Sensors<SensorModel>" "ICollection`1"
@enduml
