@startuml
class OidcConfigurationController {
    + OidcConfigurationController(clientRequestParametersProvider:IClientRequestParametersProvider, logger:ILogger<OidcConfigurationController>)
    + ClientRequestParametersProvider : IClientRequestParametersProvider <<get>>
    + GetClientRequestParameters(clientId:string) : IActionResult
}
Controller <|-- OidcConfigurationController
@enduml
